### ISSUE TITLE
Full Width page setting does not work

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-north#18]
The `Full Width` option under Page Layout is not implemented. 

@gregpriday Also an option for `Full Width, No Sidebar` would be a nice addition. What do you think?

**Comment by gregpriday** [comment]
Well spotted. I think all that's necessary here is the CSS to target the container class.

So something like

```css
.page-layout-full-width #content .container {
   width: auto;
   margin-left: 0;
   margin-right: 0;
}
```

I haven't tested that out, but it's a start.

The current `Full Width` setting excludes the sidebar, so the setting we'd want to introduce would be `Full Width, With Sidebar`.

This is where the sidebar is either displayed or not: https://github.com/siteorigin/siteorigin-north/blob/develop/page.php#L34

Feel free to implement both of these settings.
